use daily_coding_problems_rust::utils::avl_tree::*;

fn main() {
    let mut test_tree = AvlTree::new();
    println!("{}", test_tree);
    print!("\n ------------------------------------------------------ \n");
    let mut index = test_tree.insert(0);
    println!("index: {:?}", index);
    println!("{}", test_tree);
    print!("\n ------------------------------------------------------ \n");
    index = test_tree.insert(1);
    println!("index: {:?}", index);
    println!("{}", test_tree);
    print!("\n ------------------------------------------------------ \n");
    index = test_tree.insert(2);
    println!("index: {:?}", index);
    println!("{}", test_tree);
    print!("\n ------------------------------------------------------ \n");
    index = test_tree.insert(3);
    println!("index: {:?}", index);
    println!("{}", test_tree);
    print!("\n ------------------------------------------------------ \n");
    index = test_tree.insert(4);
    println!("index: {:?}", index);
    println!("{}", test_tree);
    print!("\n ------------------------------------------------------ \n");
    index = test_tree.insert(5);
    println!("index: {:?}", index);
    println!("{}", test_tree);
    print!("\n ------------------------------------------------------ \n");
    index = test_tree.insert(6);
    println!("index: {:?}", index);
    println!("{}", test_tree);
    print!("\n ------------------------------------------------------ \n");
    index = test_tree.insert(7);
    println!("index: {:?}", index);
    println!("{}", test_tree);
    print!("\n ------------------------------------------------------ \n");
    index = test_tree.insert(8);
    println!("index: {:?}", index);
    println!("{}", test_tree);
    print!("\n ------------------------------------------------------ \n");
    index = test_tree.insert(9);
    println!("index: {:?}", index);
    println!("{}", test_tree);
    print!("\n ------------------------------------------------------ \n");
}